# Generated by Django 4.2.6 on 2023-10-22 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='commets_key',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.films')),
            ],
        ),
    ]
